// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./resources/js/src/components/input/Button.vue')['default']
    Card: typeof import('./resources/js/src/components/view/Card.vue')['default']
    ImageInput: typeof import('./resources/js/src/components/input/ImageInput.vue')['default']
    Input: typeof import('./resources/js/src/components/input/Input.vue')['default']
    Navbar: typeof import('./resources/js/src/partials/Navbar.vue')['default']
    Paginate: typeof import('./resources/js/src/components/Paginate.vue')['default']
    PostCard: typeof import('./resources/js/src/page-components/posts/PostCard.vue')['default']
    PostCardHorizontal: typeof import('./resources/js/src/page-components/posts/PostCardHorizontal.vue')['default']
    PostForm: typeof import('./resources/js/src/page-components/posts/PostForm.vue')['default']
    ProfilePosts: typeof import('./resources/js/src/page-components/profile/ProfilePosts.vue')['default']
    Radio: typeof import('./resources/js/src/components/input/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./resources/js/src/components/input/Select.vue')['default']
  }
}

export {}
